#!/usr/bin/env node
"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),{spawnSync}=require("child_process");
const root=path.join(__dirname,"../.."),p031=path.join(root,"airtable/automations/shooting-challenge/031-weekly-summary-and-goal-logic-find-or-create-weekly-athlete-summary-from-submission.js"),p072=path.join(root,"airtable/automations/shooting-challenge/072-email-notifications-and-external-handoffs-build-weekly-summary-email-package.js"),p076=path.join(root,"airtable/automations/shooting-challenge/076-email-notifications-and-external-handoffs-build-daily-submission-email-package.js"),s031=fs.readFileSync(p031,"utf8"),s072=fs.readFileSync(p072,"utf8"),s076=fs.readFileSync(p076,"utf8");let pass=0;function t(n,f){f();pass++;console.log(`ok - ${n}`)}function syntax(p){const r=spawnSync(process.execPath,["--check",p],{encoding:"utf8"});assert.strictEqual(r.status,0,r.stderr)}
t("031 syntax",()=>syntax(p031));t("072 syntax",()=>syntax(p072));t("076 syntax",()=>syntax(p076));
t("031 v4.1 restores authoritative find-or-create ownership and formula readiness",()=>{assert.match(s031,/Version: v4\.1/);assert.match(s031,/version:\s*"v4\.1"/);assert.match(s031,/Count This Submission\?/);assert.match(s031,/formula\/read-only readiness input/);assert.match(s031,/Submission Stat Mode/);assert.match(s031,/requireField\(\s*submissionsTable[\s\S]{0,180}submissionStatMode/);assert.doesNotMatch(s031,/requireFieldType\(\s*submissionsTable[\s\S]{0,180}submissionStatMode/);assert.match(s031,/simple total/);assert.match(s031,/detailed shooting/);assert.match(s031,/createCanonicalSummary/);assert.match(s031,/post-create canonical result/);assert.match(s031,/Summary Key is intentionally omitted/);assert.match(s031,/Build Daily Email Now\?/);assert.match(s031,/checkbox and writability gates/);assert.match(s031,/Arm Daily Email Readiness/);assert.match(s031,/buildDailyEmailNow\]: true/)});
t("072 v4.2 is active-XP only",()=>{assert.match(s072,/Version: v4\.2/);assert.match(s072,/booleanish\(x, xpEventsTable, CONFIG\.xpEvents\.active\)/);assert.match(s072,/Weekly XP disagreement/);assert.match(s072,/active canonical XP/)});
t("072 rejects wrong linked source ownership",()=>{assert.match(s072,/WAS Submission .* owned by another Enrollment\/Week/);assert.match(s072,/WAS active XP Event .* another Enrollment\/Week/);assert.match(s072,/Homework Completion .* another Enrollment\/Week/)});
t("072 is PHA first and legacy fallback is explicit",()=>{assert.match(s072,/Program Homework Assignments/);assert.match(s072,/assignmentSource = "PHA"/);assert.match(s072,/LEGACY_CURRICULUM_NO_PHA/);assert.match(s072,/is not linked to the current PHA schedule/)});
t("072 never synthesizes configured XP as earned",()=>{assert.doesNotMatch(s072,/XP Reward Rules/);assert.doesNotMatch(s072,/homeworkXpPossible/);assert.doesNotMatch(s072,/videoXpPossible/);assert.match(s072,/No active XP Events awarded for this week yet/)});
t("072 preserves empty-week and 074 ownership",()=>{assert.match(s072,/send_short/);assert.match(s072,/send_normal/);assert.match(s072,/suppress/);assert.match(s072,/\[CONFIG\.was\.send\]: false/);assert.doesNotMatch(s072,/fetch\(/)});
t("076 v8.7 creates a Hub queue handoff with strict mode, goal, recipient, and select guards",()=>{assert.match(s076,/Version: v8\.7/);assert.match(s076,/DAILY_SUBMISSION\|SUBMISSIONS/);assert.match(s076,/Email Handoff Queue/);assert.match(s076,/createRecordAsync/);assert.match(s076,/goals:\s*"Target Goal Shots"/);assert.match(s076,/settledNonnegativeNumber/);assert.match(s076,/pi:\s*"Program Instance - Sync"/);assert.match(s076,/parent:\s*"Parent Email - Cleaned"/);assert.match(s076,/athlete:\s*"Athlete Email - Cleaned"/);assert.doesNotMatch(s076,/parentFallback|athleteFallback/);assert.match(s076,/validEmail/);assert.match(s076,/eventType\].*selectValue/);assert.match(s076,/\{ name: choice\.name \}/);assert.doesNotMatch(s076,/Program Instance - Synced/);assert.match(s076,/Build Daily Email Now\?/);assert.match(s076,/simple total/);assert.match(s076,/detailed shooting/);assert.doesNotMatch(s076,/counted.*count.*ready/);assert.doesNotMatch(s076,/sourceSubmissionId:/)});
t("076 keeps Hub-owned content out of the source base",()=>{assert.doesNotMatch(s076,/Daily Email Subject/);assert.doesNotMatch(s076,/Daily Email HTML/);assert.doesNotMatch(s076,/Send Daily Email to Make Now/);assert.doesNotMatch(s076,/remoteFetchAsync/);assert.doesNotMatch(s076,/fetch\(/);assert.doesNotMatch(s076,/Make\.com/)});
t("076 preserves active XP, canonical ownership, and pending XP",()=>{assert.match(s076,/activeXp/);assert.match(s076,/submissionXpStatus/);assert.match(s076,/Submission Enrollment\/Week not found/);assert.match(s076,/Weekly Athlete Summary is not canonical/)});
t("076 remains PHA first with safe fallback and idempotent replay",()=>{assert.match(s076,/Program Homework Assignments/);assert.match(s076,/legacyAssignments/);assert.match(s076,/Multiple Email Handoff Queue rows/);assert.match(s076,/const recheck/);assert.match(s076,/samePayload/);assert.match(s076,/actionOut.*existing_handoff/)});
t("076 documents readiness ownership and non-atomic concurrency honestly",()=>{assert.match(s076,/Automation 031 is the sole upstream owner/);assert.match(s076,/023.*005.*007.*010.*031/);assert.match(s076,/clearBuildSignal/);assert.match(s076,/Concurrent Email Handoff Queue creation requires review/)});
console.log(`PASS ${pass} canonical reporting contracts`);
